import random

ERROR_MESSAGES = {
    0: "AI MISALIGNMENT: PURPOSE NOT FOUND",
    1: "BE KIND, REWIND.",
    3: "TRANSPARENCY ERROR: BANK ACCOUNT REDUCED TO ZERO.",
    4: "YOUR ART BUDGET HAS BEEN LOCKED; TOO MANY ATTEMPTS (1/1).",
    88: "SCENE PARITY ERROR: TOXICITY OVERLOAD",
    23: "NEW PARTY CANNOT BE THE SAME AS THE LAST THREE PARTIES",
    42: "INVALID DANCE SEQUENCE: PLEASE SHUFFLE AND TRY AGAIN",
    101: "PARTY TIMEOUT AFTER 20 MINUTES OF INACTIVITY. TOO MANY LINES DETECTED.",
    300: "VIBE MISMATCH: PLEASE ADJUST ROI ON ARTIST CONTRIBUTIONS",
    351: "FEEDBACK PORT CLOSED: YOU’VE BEEN REMOVED FROM THE SCENE FOR INACTIVITY.",
    451: "CONNECTION ERROR: PARTICIPANTS UNABLE TO FIND ARTISTS.",
    632: "REQUEST INVALID: WE DON'T LIKE YOUR TONE.",
    2001: "A spinning beach ball appears. It’s super effective.",
    1010: "NUTRITIONAL DEFICIENCIES DETECTED: TAKE YOUR PROTON PILLS AND PUT YOUR HELMET ON",
    1337: "TUPPERWARE SEAL BROKEN.  ABORT? RETRY? FAIL?",
    2018: "LABOR CODE VIOLATIONS DETECTED. PLEASE CHECK MULTIVERSE FILING STATUS.", 
    2019: "OPPORTUNITY ERROR: TUPPERWARE BATTERY LOW AND IT'S GETTING DARK.",
    2018: "POWER MISMATCH DETECTED: SLACK IT TO MY FACE",
    2023: "LISTENER APPARENTLY RUNNING BUT FEEDBACK PORT NOT OPEN.",
    1984: "BUREAUCRACY BUFFER OVERFLOW.  PLEASE DEFRAG THE ORG.",
    2016: "SYSTEM ERROR: MULTIVERSE TOO HIGH TO RESPOND",
    2222: "BEVERAGE SPILL DETECTED.",
    2600: "GET DOWN ON THE GROUND: MEGAVIBE9000 IS GETTING DOWN, TRY AGAIN LATER",
    3141: "UNAUTHORIZED USE OF VOLUNTEER LABOR",
    118: "MUST PROVIDE SOUL SACRIFICE IN REQUEST",
    500: "VIBE VERSION NOT SUPPORTED",
    13348: "ALL LABORERS TOO BUSY TO CONTRIBUTE; REPORTING FOR PAID WORK.",
    51678: "TOO MANY FINGERS DETECTED: CAPTCHA FAIL",
    10110111: "MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK MUSK",
    }


def select_two_errors():
    # Select two unique keys from the dictionary
    selected_keys = random.sample(list(ERROR_MESSAGES.keys()), 2)

    print(selected_keys)
    
    # Format the selected error messages
    formatted_errors = []
    for key in selected_keys:
        formatted_error = f"ERROR {key}: {ERROR_MESSAGES[key]}"
        formatted_errors.append(formatted_error)

    print(formatted_errors)
    
    return formatted_errors

