from datetime import datetime
from tempfile import NamedTemporaryFile
from .format import text_to_img, resize_image

DEFAULT_COMPANY = "Community Capture Corporation"
DEFAULT_MOTTO = "We've got you. ;)"
DEFAULT_LOGO = "ccc/wings.png"
DEFAULT_TITLE = "MEGAVIBE 9000"
DEFAULT_TITLE_FONT = "fonts/zig.ttf"

SAMPLE_EXPERIENCE = "You rocked your head in the most amazing DJ set in your life wondering how much acid you took as the blindfold came off. You 'll always wonder who she was -- such a great painter. You found a serene oasis in the same level as Aristotle, while he’s so smart. Your doppelganger gave several different names and claimed to be the destruction of the planet itself. The best proof is that you are still disappointed."


class ReceiptImage:

    def __init__(self, filepath):
        self.filepath = filepath
        self.img = None
        self.img_tmp = None

class ReceiptText:

    def __init__(self, text, **kwargs):
        self.text = text
    
        # Default values
        defaults = {
        'font_size': 'normal',
        'font_path': None,
        'bold': False,
        'underline': 0,
        'align': 'left'
        }
    
        # Update defaults with any provided kwargs
        defaults.update(kwargs)
    
        # Set attributes
        for key, value in defaults.items():
            setattr(self, key, value)

    def render(self):
        "Returns an image generated by PIL with this text."
        return text_to_img(text, self.font_path, self.font_size, align=self.align) #  max_width=
    
    def to_dict(self):
        return {k: getattr(self, k) for k in ['font_path', 'font_size', 'bold', 'underline', 'align']}


class ExperienceReceipt:
    def __init__(self, title="MEGAVIBE\n9000", title_font=DEFAULT_TITLE_FONT, 
                    motto=DEFAULT_MOTTO, company=DEFAULT_COMPANY, logo=DEFAULT_LOGO,
                    coupon1=None, coupon2=None, experience_text=None,
                    date=None, time=None, receipt_no=None,
                ):

        # this array will hold the sequence of elements to be printed.
        self.receipt = []

        self.title = title
        self.title_font = title_font
        self.logo = logo
        self.motto = motto
        self.coupon1 = coupon1
        self.coupon2 = coupon2
        self.header = "Your Experience"
        self.body = experience_text
        self.company = company
        self.motto = motto
        self.receipt_no = receipt_no

        # date and time can be provided, or they will be set upon self.build_receipt()
        self.date = None
        self.time = None

    def set_date_time(self, date=None, time=None):
        """ If date and time are not provided, use current date and time. """
        self.date = date if date else datetime.now().strftime('%Y-%m-%d')
        self.time = time if time else datetime.now().strftime('%H:%M:%S')

    def set_receipt_no(self):
        #todo: change this to 2999 epoch timestamp
        if not self.receipt_no:
            self.receipt_no = datetime.timestamp(datetime.now())

    def build_receipt(self):
        """ This function builds the receipt as a sequential array of Receipt* objects,
        which can be rendered using a BasePrinter object (e.g. through PIL to an 
        image, or through an ESC/POS thermal printer.
        """

        self.receipt = []
        self.set_date_time()

        # Top matter: store name, date, time.
        # 
        # If any title or header contains a "\n", split these up into sequential
        # objects to avoid making the text_to_img processor have to figure it out.
        
        title_parts = self.title.split("\n")
        for part in title_parts:
            self.receipt.append(ReceiptText(part, font_path=self.title_font, font_size="xlarge", align="center"))
        
        self.receipt.append(ReceiptText(f"Date: {self.date}"))
        self.receipt.append(ReceiptText(f"Time: {self.time}"))

        self.receipt.append(ReceiptText(self.header, font_size="large", bold=True))

        # -- Experience section begins -- 
        # 
        # break the body down into parts so that coupons can be inserted.
        if not self.body:
            self.body = SAMPLE_EXPERIENCE

        part1 = self.body.split(".")[0:2]
        part2 = self.body.split(".")[3:]

        self.receipt.append(ReceiptText("{}".format((". ").join(part1) + ". ")))
        if self.coupon1:
            self.receipt.append(ReceiptImage(self.coupon1))
        self.receipt.append(ReceiptText("{}".format((". ").join(part2))))

        # -- end of Experience section --
        
        # -- Company footer should be centered. Name -> "motto" -> logo.
        self.receipt.append(ReceiptText(self.company, align="center", bold=True, letter_spacing=15,
                                        underline=2, font_size="medium"))
        self.receipt.append(ReceiptText(self.motto))
        self.receipt.append(ReceiptImage(self.logo))

        if self.coupon2:
            self.receipt.append(ReceiptImage(self.coupon2))

        self.set_receipt_no()
        self.receipt.append(ReceiptText(f"Receipt No.: {self.receipt_no}"))


